---
title: "First Class"
output: html_notebook
---

## Packages
```{r}
library(tidyverse)
library(magrittr)
```


## Importing dataset from txt

```{r}
setwd("~/Insync/leonardogloria@uenf.br/Google Drive/MENTORIA_R/Andres_R_class/R_class/Data")
datasett <- read.table("dataset.txt", h = T)

head(datasett)
```

## Deleting columns

```{r}
datasett %<>%
  select(-DIM)
```

## Rename columns

```{r}
datasett %<>%
  rename(farm=ID_FAZENDA, animal=BRINCO, season=EPOCA_PARTO,MY=Y,DIM=X)

```

## sorting dataset

```{r}
datasett %<>%
  arrange(animal)

```

## Creating columns 

```{r}
datasett %<>%
  mutate(CG=paste0(NP,NL)) 
```

## Creating new dataset from another dataset

```{r}
dataset2 <- datasett %>%
  select(animal,DIM,CG,MY)
```

## Calculating mean and standard deviation by CG
```{r}
dataset2 %>% 
  group_by(CG) %>%
  summarise(`Mean` = mean(MY), `SD` = sd(MY))
```

## All descriptive analysis

```{r}
descript <- dataset2 %>%
  select(CG,MY) %>% 
  dplyr::group_by(CG) %>%
  rstatix::get_summary_stats(type="full", show=c("n","mean","sd", "min","max"))
```

## Data visualization
```{r}
ggplot(data = dataset2) + 
  geom_point(mapping = aes(x = DIM, y = MY,color=CG))

```

